version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - MONGO_AUTH=no
      - MONGO_PORT=27017
      - MONGO_DB=libraryDB
      - MONGO_HOST=127.0.0.1
      - WAIT_FOR=mongo:27017
    networks:
      - nw
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - nw
networks:
  nw:
