spring:
  data:
    mongodb:
      authentication-database: no
      port: 27017
      host: 127.0.0.1
      database: libraryDB
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  file:
    name: "target/app.log"
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: DEBUG
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      metrics:
        rollingStats:
          timeInMilliseconds: 15000
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 6000